Styling
Ugboaja-Uchechi/react-bookstore pull request #5
Opened 2021-11-18 17:07 UTC by Ugboaja-Uchechi

2021-11-18 21:18 UTC, Ugboaja-Uchechi commented
All linter checks have passed.
No merge conflicts

2021-11-19 00:13 UTC, omar-labana requested changes
Hi @Ugboaja-Uchechi, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 00:13 UTC, omar-labana commented on src/components/Books-Input.js
> +        <h3>ADD NEW BOOK</h3>
- [ ] Please make sure to correctly align this form horizontally.
Your styling
![image](https://user-images.githubusercontent.com/33767951/142516487-f8985ede-f169-4e5d-92af-3644ff6ed236.png)

2021-11-19 00:13 UTC, omar-labana commented on src/components/Books-Page.js
> +              <span className="line" />
- [ ] Kindly make sure to correctly position each section according to the design.|
Reference Design
![image](https://user-images.githubusercontent.com/33767951/142516687-1cf1894c-3d13-487b-b5e4-3167f78ad54c.png)
Your styling
![image](https://user-images.githubusercontent.com/33767951/142516726-fae8be9b-4553-472d-915a-e0245381496d.png)

2021-11-19 08:33 UTC, Ugboaja-Uchechi commented
Fixed all code reviews as best as I could.

2021-11-19 09:46 UTC, Davidosky007 requested changes
## Hi @Ugboaja-Uchechi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 09:46 UTC, Davidosky007 commented on src/components/Books-Page.js
> +              <span className="line" />
* Hi, @Ugboaja-Uchechi like the previous reviewer pointed out your design isn't properly aligned, from the screenshot below all `book cards` should be on a straight line
* ## ORIGINAL DESIGN 
![uogo](https://user-images.githubusercontent.com/52497246/142601317-b2cd81b6-1cab-4a37-a03f-f0668e9cbff7.png)
* ## YOURS 
* The add button, the input area should be on a straight line and should be on a straight line as the `book cards` above it 
![image](https://user-images.githubusercontent.com/52497246/142601439-c61256f7-1508-4067-b525-503a1c06b217.png)

2021-11-19 11:42 UTC, Ugboaja-Uchechi commented
Built this project for a screen size of 1440px

2021-11-19 11:51 UTC, Emmyn5600 approved these changes
Hi @Ugboaja-Uchechi 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-19 12:00 UTC, merged